# permissions for end users to view monitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: monitoring-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: monitoring-operator
    app.kubernetes.io/part-of: monitoring-operator
    app.kubernetes.io/managed-by: kustomize
  name: monitoring-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - monitorings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - monitorings/status
  verbs:
  - get
